name: Create test_push Directory

on:
  push:
    branches:
      - dev  # This will trigger the action when code is pushed to the dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code (if necessary, but not used here for the directory creation)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Create test_push folder in the home directory of the remote server
      - name: Copy application folder to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.AWS_DEV_SERVER_HOST }}
          username: ${{ secrets.AWS_DEV_SERVER_USER }}
          key: ${{ secrets.AWS_DEV_SERVER_SSH_KEY }}
          source: |
            database/
            resources/
            app/
            routes/
          target: /home/ubuntu/  # Target path on the remote server
          recursive: true  # Recursively copy directories
          overwrite: true  # Overwrite existing files
          debug: true      # Enable detailed logging


