name: Create test_push Directory

on:
  push:
    branches:
      - dev  # This will trigger the action when code is pushed to the dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Setup node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 1: Checkout the code (if necessary, but not used here for the directory creation)
      - name: Checkout repository
        uses: actions/checkout@v3

          # Step 2: List repository files (optional, for debugging)
      - name: List repository files
        run: ls -R

        # Step 2: Create test_push folder in the home directory of the remote server
      - name: Copy application folder to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.AWS_DEV_SERVER_HOST }}
          username: ${{ secrets.AWS_DEV_SERVER_USER }}
          key: ${{ secrets.AWS_DEV_SERVER_SSH_KEY }}
          sync: true
          args: "-r app/ routes/ database/"
          target: /home/ubuntu/
          port: 22
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          debug: true

        #- name: Copy to Remote Server
        #  uses: pierrickdelrieu/scp-action@v0.1.0
        #  with:
        #    host: ${{ secrets.AWS_DEV_SERVER_HOST }}
        #    ssh_username: ${{ secrets.AWS_DEV_SERVER_USER }}
        #    ssh_key: ${{ secrets.AWS_DEV_SERVER_SSH_KEY }}
        #    ssh_port: 22
        #    source_dir: database/
        #    destination_dir: /home/ubuntu/
        #    rm: true


