name: Create test_push Directory

on:
  pull_request:
    types: [closed]
    branches:
      - dev  # This will trigger the action when code is pushed to the dev branch

jobs:
  deploy:
    if: github.event.pull_request.merged == true  # Ensure the pull request was merged
    runs-on: ubuntu-latest

    steps:
      # Setup node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 1: Checkout the code (if necessary, but not used here for the directory creation)
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Adjust PHP version if necessary
          extensions: mbstring, bcmath, gd, soap, xml, curl
      
      - name: Copy Vitfe Backend
        uses: picodebr/copy-action@v1
        with:
          ssh_host: ${{ secrets.AWS_DEV_SERVER_HOST }}
          ssh_user: ${{ secrets.AWS_DEV_SERVER_USER }}
          ssh_key: ${{ secrets.AWS_DEV_SERVER_SSH_KEY }}
          source: ./*
          destination: /home/${{ secrets.AWS_DEV_SERVER_USER }}/vitfe-backend

          # - name: Install Composer dependencies on server
          #   run: ssh -i ${{ secrets.AWS_DEV_SERVER_SSH_KEY }} ${{ secrets.AWS_DEV_SERVER_USER }}@${{ secrets.AWS_DEV_SERVER_HOST }} "cd /home/${{ secrets.AWS_DEV_SERVER_USER }}/laravel_project && composer install --no-dev --prefer-dist --optimize-autoloader"

          # - name: Run database migrations on server
          #   run: ssh -i ${{ secrets.AWS_DEV_SERVER_SSH_KEY }} ${{ secrets.AWS_DEV_SERVER_USER }}@${{ secrets.AWS_DEV_SERVER_HOST }} "cd /home/${{ secrets.AWS_DEV_SERVER_USER }}/laravel_project && php artisan migrate --force"

          # - name: Clear caches and optimize on server
          #   run: ssh -i ${{ secrets.AWS_DEV_SERVER_SSH_KEY }} ${{ secrets.AWS_DEV_SERVER_USER }}@${{ secrets.AWS_DEV_SERVER_HOST }} "cd /home/${{ secrets.AWS_DEV_SERVER_USER }}/laravel_project && php artisan config:cache && php artisan route:cache && php artisan view:cache"

          # - name: Symlink storage folder on server
          #   run: ssh -i ${{ secrets.AWS_DEV_SERVER_SSH_KEY }} ${{ secrets.AWS_DEV_SERVER_USER }}@${{ secrets.AWS_DEV_SERVER_HOST }} "cd /home/${{ secrets.AWS_DEV_SERVER_USER }}/laravel_project && php artisan storage:link"

          # - name: Restart web server on server (if necessary)
          #   run: ssh -i ${{ secrets.AWS_DEV_SERVER_SSH_KEY }} ${{ secrets.AWS_DEV_SERVER_USER }}@${{ secrets.AWS_DEV_SERVER_HOST }} "sudo service nginx reload"





          # - name: Copy app folder
          #   uses: picodebr/copy-action@v1
          #   with:
          #     ssh_host: ${{ secrets.AWS_DEV_SERVER_HOST }}
          #     ssh_user: ${{ secrets.AWS_DEV_SERVER_USER }}
          #     ssh_key: ${{ secrets.AWS_DEV_SERVER_SSH_KEY }}
          #     source: app/
          #     destination: /home/${{ secrets.AWS_DEV_SERVER_USER }}/app

          # - name: Copy routes folder
          #   uses: picodebr/copy-action@v1
          #   with:
          #     ssh_host: ${{ secrets.AWS_DEV_SERVER_HOST }}
          #     ssh_user: ${{ secrets.AWS_DEV_SERVER_USER }}
          #     ssh_key: ${{ secrets.AWS_DEV_SERVER_SSH_KEY }}
          #     source: routes/
          #     destination: /home/${{ secrets.AWS_DEV_SERVER_USER }}/routes

          # - name: Copy resources folder
          #   uses: picodebr/copy-action@v1
          #   with:
          #     ssh_host: ${{ secrets.AWS_DEV_SERVER_HOST }}
          #     ssh_user: ${{ secrets.AWS_DEV_SERVER_USER }}
          #     ssh_key: ${{ secrets.AWS_DEV_SERVER_SSH_KEY }}
          #     source: resources/
          #     destination: /home/${{ secrets.AWS_DEV_SERVER_USER }}/resources
